name: Build Binaries

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller typer rich python-dotenv requests

      - name: Build binary with PyInstaller
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --onefile -n sumsnap-windows src/main.py
            mv dist/sumsnap-windows.exe dist/sumsnap-windows.exe
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            pyinstaller --onefile -n sumsnap-macos src/main.py
            mv dist/sumsnap-macos dist/sumsnap-macos
          else
            pyinstaller --onefile -n sumsnap-linux src/main.py
            mv dist/sumsnap-linux dist/sumsnap-linux
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sumsnap-${{ runner.os }}
          path: |
            dist/sumsnap-*

  release:
    name: Create Pre-release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Set Release Version
        id: version
        run: |
          echo "RELEASE_VERSION=pre-release-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Get commit messages since last release
        id: changelog
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            git log --pretty=format:"- %s" > changes.txt
          else
            git log $LAST_TAG..HEAD --pretty=format:"- %s" > changes.txt
          fi
          echo 'RELEASE_BODY<<EOF' >> $GITHUB_ENV
          cat changes.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create GitHub Release (pre-release)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: "Pre-release ${{ env.RELEASE_VERSION }}"
          prerelease: true
          body: ${{ env.RELEASE_BODY }}
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
