name: Build Binaries

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller typer rich python-dotenv requests

      - name: Build binary with PyInstaller
        run: |
          pyinstaller --onefile -n sumsnap main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sumsnap-${{ runner.os }}
          path: dist/sumsnap*
